### PR TITLE
Update AEAD handling

### PR DESCRIPTION
**Pull request by franziskuskiefer**
In this PR I change when the counter gets increased. Before it was not increased when the decryption failed (invalid tag). Now the counter is increased even if the decryption fails.

### CODE REVIEW

**Comment by raphaelrobert** [comment]
I'm concerned this could introduce another attack:

If an attacker send completely bogus messages to a recipient, the recipient will now blindly increase the counter. When the recipient afterwards receives a valid message, they will not be able to decrypt it because of FS.

**Comment by franziskuskiefer** [comment]
> If an attacker send completely bogus messages to a recipient, the recipient will now blindly increase the counter. When the recipient afterwards receives a valid message, they will not be able to decrypt it because of FS.

Sure, with the mechanisms currently available (the counter). There will always be one attack or the other.

**Comment by raphaelrobert** [comment]
The counter is covered by the MAC, so an attacker couldn't manipulate the counter with bogus messages (where the verification fails) until now. With this PR an attacker can increase the counter by sending any random message.

**Comment by franziskuskiefer** [comment]
Right, but at the moment an attacker can invalidate messages and thus produce a `TooDistantFuture` error that (if performed in both directions) is unrecoverable.

**Comment by franziskuskiefer** [comment]
Fixes https://github.com/wireapp/security/issues/22
@raphaelrobert how do you want to proceed here?

**Comment by franziskuskiefer** [comment]
@raphaelrobert can you review? Not counting anymore on failure, but properly handling decryption.

**Review by raphaelrobert — APPROVED** [review]

**Comment by raphaelrobert** [comment]
If we don't do any other changes we should bump the version number.

**Pull request merged**
